// The route model every arm is built from.
//
// A route is a method and a list of path segments. A segment is a literal, a named
// parameter that matches one non-empty segment, or a trailing catch-all that matches the
// rest of the path (one or more segments). Each arm converts this structure into its own
// pattern syntax; nothing is parsed from text on the way.
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <string_view>
#include <vector>

// The instruction set of this build (generated by cmake/isa.cmake). Included here so that every
// target that compiles the harness's core has it among its compiled inputs.
#include "rb_isa.h"

namespace rb {

using RouteId = std::uint32_t;
inline constexpr RouteId kNoRoute = 0xFFFF'FFFFu;           // no route matches: 404
inline constexpr RouteId kMethodNotAllowed = 0xFFFF'FFFEu;  // only other methods' routes match: 405
inline constexpr std::size_t kMaxParams = 8;

enum class Method : std::uint8_t { Get, Post, Put, Delete, Patch, Head, Options };
inline constexpr std::size_t kMethods = 7;
std::string_view method_name(Method m);

enum class Seg : std::uint8_t { Literal, Param, Rest };

struct Segment {
    Seg kind = Seg::Literal;
    std::string text;  // the literal, or the parameter's name
};

struct Route {
    Method method = Method::Get;
    std::vector<Segment> segs;
};

// Canonical text: "/users/{p0}/files/{*p1}". Used for table digests and logs only.
std::string render(const Route& route);

// Parses canonical text (the probe tables are written in it). Throws std::invalid_argument.
Route parse_route(Method method, std::string_view text);

// What a lookup yields besides the route id: the captured values in pattern order, as views
// into memory the arm owns or into the query path. Valid until the arm's next lookup.
struct Captures {
    std::array<std::string_view, kMaxParams> v{};
    std::uint8_t n = 0;
};

}  // namespace rb
