# The instruction set every arm is compiled for: the build host's own (hypotheses-round2.md,
# section 2 and Appendix B). Included by rbench (bench/CMakeLists.txt) and by the paper's root
# project (the minimal server and h6_targets), before any target or fetched project is defined:
#   C and C++   -march=${RB_MARCH} (default native), on every target of the build, the fetched
#               libraries included (a directory compile option, inherited by their projects);
#   Rust        -C target-cpu=${RB_RUST_TARGET_CPU} (default native; cmake/ffi-rust.cmake);
#   Go          GOAMD64 at the highest x86-64 level the host supports, as glibc's dynamic loader
#               reports it (ld.so --help), unless RB_GOAMD64 names one (cmake/ffi-go.cmake); the
#               C that cgo compiles gets -march=${RB_MARCH} through CGO_CFLAGS.
# What these resolve to on the build host (clang's target CPU and features, rustc's CPU, the
# GOAMD64 level) is written to BUILD/rb-isa/rb_isa.h. The harness's core/route.hpp and the
# server's route.hpp and arm_v1.hpp include it, so the file is a compiled input of every
# first-party target, generated into the build tree: lab/bin/inputs_hash.py hashes it, and a
# build for another instruction set cannot pass the records gate.
include_guard(GLOBAL)

set(RB_MARCH "native" CACHE STRING "-march of every C and C++ target (empty: none)")
set(RB_RUST_TARGET_CPU "native" CACHE STRING "-C target-cpu of the Rust arms (empty: rustc's default)")
set(RB_GOAMD64 "" CACHE STRING "GOAMD64 of the Go arms (empty: the highest level the host supports)")

set(RB_ISA_TARGET_CPU "")
set(RB_ISA_FEATURES "")
if(RB_MARCH)
    add_compile_options(-march=${RB_MARCH})
    execute_process(COMMAND "${CMAKE_CXX_COMPILER}" -march=${RB_MARCH} "-###" -c -x c++ /dev/null -o /dev/null
                    ERROR_VARIABLE _isa_driver OUTPUT_QUIET RESULT_VARIABLE _isa_rc)
    if(NOT _isa_rc EQUAL 0 OR NOT _isa_driver MATCHES "\"-target-cpu\" \"([^\"]+)\"")
        message(FATAL_ERROR "isa: ${CMAKE_CXX_COMPILER} does not resolve -march=${RB_MARCH}")
    endif()
    set(RB_ISA_TARGET_CPU "${CMAKE_MATCH_1}")
    string(REGEX MATCHALL "\"-target-feature\" \"[^\"]+\"" _isa_feats "${_isa_driver}")
    foreach(_f IN LISTS _isa_feats)
        string(REGEX REPLACE "\"-target-feature\" \"([^\"]+)\"" "\\1" _f "${_f}")
        string(APPEND RB_ISA_FEATURES "${_f},")
    endforeach()
    string(REGEX REPLACE ",$" "" RB_ISA_FEATURES "${RB_ISA_FEATURES}")
endif()

set(RB_ISA_RUST_CPU "")
find_program(RB_ISA_RUSTC rustc)
if(RB_RUST_TARGET_CPU STREQUAL "native")
    set(RB_ISA_RUST_CPU "unresolved (no rustc)")
    if(RB_ISA_RUSTC)
        execute_process(COMMAND "${RB_ISA_RUSTC}" --print target-cpus OUTPUT_VARIABLE _isa_rust ERROR_QUIET)
        if(_isa_rust MATCHES "currently ([A-Za-z0-9_-]+)")
            set(RB_ISA_RUST_CPU "${CMAKE_MATCH_1}")
        endif()
    endif()
elseif(RB_RUST_TARGET_CPU)
    set(RB_ISA_RUST_CPU "${RB_RUST_TARGET_CPU}")
endif()

set(RB_ISA_GOAMD64 "${RB_GOAMD64}")
if(NOT RB_ISA_GOAMD64)
    execute_process(COMMAND /lib64/ld-linux-x86-64.so.2 --help OUTPUT_VARIABLE _isa_ld ERROR_QUIET)
    foreach(_level 4 3 2)
        if(_isa_ld MATCHES "x86-64-v${_level} \\(supported")
            set(RB_ISA_GOAMD64 "v${_level}")
            break()
        endif()
    endforeach()
    if(NOT RB_ISA_GOAMD64)
        set(RB_ISA_GOAMD64 "v1")
    endif()
endif()

set(_isa_out "${CMAKE_BINARY_DIR}/rb-isa/rb_isa.h")
set(_isa_content "// Generated by bench/cmake/isa.cmake: the instruction set this build compiles every arm for.
#pragma once
#define RB_ISA_MARCH \"${RB_MARCH}\"
#define RB_ISA_TARGET_CPU \"${RB_ISA_TARGET_CPU}\"
#define RB_ISA_FEATURES \"${RB_ISA_FEATURES}\"
#define RB_ISA_RUST_TARGET_CPU \"${RB_RUST_TARGET_CPU}\"
#define RB_ISA_RUST_CPU \"${RB_ISA_RUST_CPU}\"
#define RB_ISA_GOAMD64 \"${RB_ISA_GOAMD64}\"
")
if(EXISTS "${_isa_out}")
    file(READ "${_isa_out}" _isa_old)
endif()
if(NOT _isa_old STREQUAL _isa_content)
    file(WRITE "${_isa_out}" "${_isa_content}")
endif()
include_directories("${CMAKE_BINARY_DIR}/rb-isa")
message(STATUS "isa: -march=${RB_MARCH} (clang target CPU ${RB_ISA_TARGET_CPU}), Rust target-cpu "
               "${RB_RUST_TARGET_CPU} (${RB_ISA_RUST_CPU}), GOAMD64=${RB_ISA_GOAMD64}")
