#!/usr/bin/env python3
"""The paper's macros for round 2 (results/macros.tex), from analysis/analyse.py's summary.json only.

    macros.py SUMMARY_JSON [--out results/macros.tex]

Every number the paper states comes from here, and every macro here comes from summary.json,
which analysis/analyse.py writes from the run: nothing is typed in by hand. The rounding of each
kind of number is analysis/macros_util.py's. Names are letters only: a hypothesis (HOne ... HSeven),
then what is counted or stated; per-cell macros add the shape and size words of macros_util
(HOneRatioStaticTen, HSevenHighRestThousand, ...). Decisions are the words "holds" and "does not
hold". A macro whose source is missing from the summary (a part of the analysis not run, such as
H6 without its T1 run) is not written, so LaTeX stops on it rather than printing a stale value.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from macros_util import Macros, cell_word, count, listing, ratio, scientific, tt

HEAD = "% Generated by analysis/macros.py from analysis/analyse.py's summary.json. Do not edit.\n"


def verdict(b: bool) -> str:
    return "holds" if b else "does not hold"


def cell_list(names: list[str]) -> str:
    """"shape m" items as the paper names cells."""
    out = []
    for n in names:
        shape, _, m = n.rpartition(" ")
        out.append(f"{tt(shape)} at $m={count(int(m))}$" if m.isdigit() else tt(n))
    return listing(out) if out else "none"


def design(mc: Macros, s: dict) -> None:
    mc.add("RoundTwoReps", count(s["reps"]), "processes per cell")
    mc.add("RoundTwoResamples", count(s["resamples"]), "bootstrap resamples")
    mc.add("RoundTwoResamplingSeed", str(s["resampling_seed"]))
    prov = s.get("provenance") or {}
    if prov.get("seed"):
        mc.add("RoundTwoOrderSeed", prov["seed"], "the shuffle of the cell order, provenance.txt")
    if prov.get("regexmatcher_commit"):
        mc.add("RegexMatcherCommit", tt(prov["regexmatcher_commit"][:9]))
    if prov.get("code_commit"):
        mc.add("RbenchCommit", tt(prov["code_commit"][:9]))
    if prov.get("compiler"):
        mc.add("RunCompiler", prov["compiler"])
    if prov.get("pins_sha256"):
        mc.add("PinsSha", tt(prov["pins_sha256"].split()[0][:12]))


def h1(mc: Macros, s: dict) -> None:
    h = s["h1"]
    mc.add("HOneCells", count(h["cells"]))
    mc.add("HOneTested", count(h["tested"]))
    mc.add("HOnePassed", count(h["passed"]), "cells passing under both computations")
    mc.add("HOnePassedBoot", count(h["passed_boot"]))
    mc.add("HOnePassedSign", count(h["passed_sign"]))
    mc.add("HOneDisagree", count(h["disagree"]))
    mc.add("HOneNeed", count(h["need"]))
    mc.add("HOneCap", ratio(h["cap"]).rstrip("0").rstrip("."))
    mc.add("HOneOverCap", count(h["over_cap"]))
    mc.add("HOneSuperior", count(h["superior"]))
    mc.add("HOneFails", count(h["fails"]))
    if h.get("largest_ci_high") is not None:
        mc.add("HOneMaxHigh", ratio(h["largest_ci_high"]), "largest clustered 95% upper bound")
    mc.add("HOneVerdict", verdict(h["holds"]))
    for r in s.get("h1_cells", []):
        if r.get("status") != "tested":
            continue
        w = cell_word(r["shape"], int(r["m"]))
        mc.add(f"HOneRatio{w}", ratio(r["ratio"]))
        mc.add(f"HOneLow{w}", ratio(r["ci_low"]))
        mc.add(f"HOneHigh{w}", ratio(r["ci_high"]))
        mc.add(f"HOneSignX{w}", count(r["sign_x"]))
        mc.add(f"HOneFastest{w}", tt(r["fastest"]))
        mc.add(f"HOnePHolm{w}", scientific(max(r["p_boot_holm"], r["p_sign_holm"])),
               "the larger of the two Holm-adjusted p-values")
        # The raw p-values beside the adjusted ones, so the text can show what Holm's step-down did
        # to a cell (its multiplier depends on how many cells of the family are tested).
        mc.add(f"HOnePSignRaw{w}", scientific(r["p_sign"]), "exact sign test, before Holm")
        mc.add(f"HOnePSignHolm{w}", scientific(r["p_sign_holm"]), "exact sign test, Holm-adjusted")
        mc.add(f"HOnePBootRaw{w}", scientific(r["p_boot"]), "clustered bootstrap, before Holm")
        mc.add(f"HOnePBootHolm{w}", scientific(r["p_boot_holm"]), "clustered bootstrap, Holm-adjusted")


def h2(mc: Macros, s: dict) -> None:
    h = s["h2"]
    mc.add("HTwoCells", count(h["cells"]))
    mc.add("HTwoJudged", count(h["judged"]))
    mc.add("HTwoHeld", count(h["held"]))
    mc.add("HTwoLost", count(len(h["lost"])))
    mc.add("HTwoLostCells", cell_list(h["lost"]))
    mc.add("HTwoVerdict", verdict(h["holds"]))


def h3(mc: Macros, s: dict) -> None:
    v = s["h3"]["arms"]["regexmatcher-v2"]
    mc.add("HThreeProcesses", count(v["processes"]))
    mc.add("HThreeVerdict", verdict(s["h3"]["holds"]))


def h4(mc: Macros, s: dict) -> None:
    h = s["h4"]
    mc.add("HFourJudged", count(h["judged"]))
    mc.add("HFourLost", count(len(h["lost"])))
    mc.add("HFourLostBuild", count(h["lost_build"]))
    mc.add("HFourLostSecond", count(h["lost_1s"]))
    mc.add("HFourLostHeap", count(h["lost_heap"]))
    mc.add("HFourVerdict", verdict(h["holds"]))


def h5(mc: Macros, s: dict) -> None:
    h = s["h5b"]
    mc.add("HFiveBLookups", count(h["v2_lookups"]))
    mc.add("HFiveBVerdict", verdict(h["holds"]))


def h6(mc: Macros, s: dict) -> None:
    if "h6" not in s:
        return
    h = s["h6"]
    mc.add("HSixCells", count(h["cells"]))
    mc.add("HSixAHeld", count(h["a_held"]))
    mc.add("HSixBHeld", count(h["b_held"]))
    mc.add("HSixAVerdict", verdict(h["a_holds"]))
    mc.add("HSixBVerdict", verdict(h["b_holds"]))
    for r in s.get("h6_cells", []):
        if r.get("status") != "tested":
            continue
        shape, _, m = r["cell"].rpartition("-")
        w = cell_word(shape, int(m))
        mc.add(f"HSixRatio{w}", ratio(r["ratio"]))
        mc.add(f"HSixLow{w}", ratio(r["ratio_ci_low"]))
        mc.add(f"HSixPairs{w}", count(r["pairs"]))
        if "carry" in r:
            mc.add(f"HSixCarry{w}", ratio(r["carry"]))
            mc.add(f"HSixCarryLow{w}", ratio(r["carry_ci_low"]))


def h7(mc: Macros, s: dict) -> None:
    h = s["h7"]
    mc.add("HSevenCells", count(h["cells"]))
    mc.add("HSevenHeld", count(h["held"]))
    mc.add("HSevenHeldBoot", count(h["held_boot"]))
    mc.add("HSevenHeldSign", count(h["held_sign"]))
    if h.get("largest_ci_high") is not None:
        mc.add("HSevenMaxHigh", ratio(h["largest_ci_high"]))
    if h.get("fewest_below") is not None:
        mc.add("HSevenFewestBelow", count(h["fewest_below"]), "fewest pairs below 1.02 in a cell")
    mc.add("HSevenVerdict", verdict(h["holds"]))
    for r in s.get("h7_cells", []):
        if r.get("status") != "tested":
            continue
        w = cell_word(r["shape"], int(r["m"]))
        mc.add(f"HSevenRatio{w}", ratio(r["ratio"]))
        mc.add(f"HSevenHigh{w}", ratio(r["ci_high"]))
        mc.add(f"HSevenSignX{w}", count(r["sign_x"]))


def render(summary: dict) -> str:
    mc = Macros()
    for part in (design, h1, h2, h3, h4, h5, h6, h7):
        part(mc, summary)
    return HEAD + mc.text()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("summary", type=Path)
    ap.add_argument("--out", type=Path)
    a = ap.parse_args()
    text = render(json.loads(a.summary.read_text(encoding="utf-8")))
    if a.out:
        a.out.write_text(text, encoding="utf-8")
    else:
        print(text, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
