#!/usr/bin/env python3
"""The paper's second macro file for round 2 (results/round2/macros-paper.tex).

    paper_macros.py [--results results/round2] [--run RUN_DIR] [--out results/round2/macros-paper.tex]

analysis/macros.py writes results/round2/macros.tex from summary.json alone, as the frozen
pre-specification (hypotheses-round2.md, section 9) says, and that file is not touched here. The
paper also states numbers that summary.json does not carry: the per-cell rows of its tables,
H7's costs, the exploratory runs, the ablation arm, the design's constants, the tool versions and
the archives. This script writes them, from these sources only:

- the files analysis/analyse.py and analysis/explore_summary.py wrote into results/round2
  (summary.json and the CSVs);
- the evidence of the runs in the Papers repository (lab/evidence/2026-10-01-*): the frozen
  analysis of the main grid before the repeated check (analysis-asis/summary.json), the MSVC costs
  (tables.jsonl), the archives' sha256 files and the run's rb_isa.h and pin.json;
- the exploratory follow-up of H7 (explore_ct_heap.csv, analysis/ct_heap_summary.py) and its
  archive's sha256 (lab/evidence/2026-10-02-L-exploratory-ct-heap);
- the sanitizer records the numbers rest on (lab/sanitizer-records);
- the raw main grid's toolchain.txt and cells.jsonl (--run), for the tool versions and the
  prefix of the ring that H6(b)'s v1 times rest on;
- bench/cmake/pins.cmake, bench/arms/rust/Cargo.lock and bench/arms/go/go.mod, against which every
  version string below is checked;
- the constants of the frozen text, typed below with the section that fixes each.

It never reads results/ of round 1, whose macro names are the same. The rounding of each kind of
number is analysis/macros_util.py's. The script also checks the facts the paper states in words
(no cell where v2 or the fastest competitor ran on a prefix of the ring, no competitor over the
time budget, a BCa acceleration of zero) and stops if one is false.
"""

from __future__ import annotations

import argparse
import json
import math
import re
import statistics
from collections import Counter
from pathlib import Path

from macros_util import (SHAPE_WORD, SIZE_WORD, Macros, cell_word, count, fixed, instructions, multiple,
                         nanoseconds, per_lookup, ratio, read_csv, scientific, tt)

HERE = Path(__file__).resolve().parent
PAPER = HERE.parent
PAPERS = PAPER.parent.parent
EVIDENCE = PAPERS / "lab/evidence"
RECORDS = PAPERS / "lab/sanitizer-records"
HEAD = ("% Generated by analysis/paper_macros.py from results/round2, the runs' evidence and records, and the\n"
        "% frozen constants it names. Do not edit. The decisions' macros are in macros.tex.\n")

SHAPES = ["static", "param-last", "param-first", "rest", "wild", "mixed-disjoint", "mixed-overlap"]
SIZES = [10, 100, 1000, 10000, 100000]

# Constants of the frozen pre-specification (hypotheses-round2.md at 9d7e8fe), by section.
FROZEN = {
    "PassBudgetSeconds": ("0.25", "section 3, pass_budget_s"),
    "PassMinQueries": ("16", "section 3"),
    "VerifyBudgetSeconds": ("120", "section 3, verify_budget_s"),
    "VerifyMinQueries": ("64", "section 3"),
    "SupMargin": ("1.00", "section 6, H1 superiority"),
    "Alpha": ("0.025", "section 5, one-sided, family-wise"),
    "Level": ("95", "section 5, the two-sided interval"),
    "HeapFactor": ("2", "section 6, H4"),
    "BuildLimitSeconds": ("1", "section 6, H4"),
    "CarryBound": ("0.5", "section 6, H6(b)"),
    "NegCases": ("17", "section 6, H5(a)"),
    "ConstexprSteps": ("33{,}554{,}432", "section 6, H7"),
    "StepsStart": ("1{,}048{,}576", "section 6, H7, the start of the budget search"),
    "VerifyJobsFirst": ("16", "revision log, 2026-10-01"),
    "VerifyJobsRepeat": ("4", "revision log, 2026-10-01"),
    "VerifyMemoryGB": ("15", "revision log, 2026-10-01: L's memory"),
    "VerifyCheckGB": ("2", "revision log, 2026-10-01: up to 2 GB per check"),
    "HostWCpu": ("AMD Ryzen 5 3600", "Words: W"),
    "HostLArch": ("Zen 3", "Words: L"),
    "HostWArch": ("Zen 2", "Words: W"),
    "MissPermille": ("500", "section 7, MISS=500"),
    "LongWordMin": ("12", "section 7, the long vocabulary"),
    "LongWordMax": ("24", "section 7"),
    "KeyBytes": ("8", "section 7: v2 keys a segment on its first 8 bytes"),
    "GithubRoutes": ("203", "section 7"),
    "ExploreReps": ("3", "section 7, R = 3"),
}
# H6's design (section 6, H6), the same file.
H6_FROZEN = {
    "HSixServerCpu": "14", "HSixServerSibling": "15", "HSixGenCpuFirst": "2", "HSixGenCpuLast": "13",
    "HSixConnections": "64", "HSixWarmupSeconds": "1", "HSixWindowSeconds": "5", "HSixBodyBytes": "13",
    "HSixMinPairs": "6", "HSixMaxPairs": "20", "HSixStopLow": "0.98", "HSixStopHigh": "1.02",
    "HSixStopHalfWidthPct": "1", "HSixErrorSharePct": "0.1", "HSixGenBusyPct": "90", "HSixMhzDriftPct": "2",
}
# The limits of v2's patterns (RegexMatcher d1d73e9, include/matcher/route/config.hpp), and the
# linear scan of a node's literal children (route/table.hpp, kLinearEdges).
V2_LIMITS = {"MaxSegments": "32", "MaxParams": "16", "LinearEdges": "8", "MethodSlots": "9", "PageBytes": "4{,}096"}

# Competitors (hypotheses-round2.md, section 2): key, name in text, language, version as the paper
# prints it, and the string that must occur in the pin's file.
COMPETITORS = [
    ("crow", "Crow", "C++", "v1.3.4", "Crow v1.3.4"),
    ("drogon", "Drogon", "C++", "v1.9.13", "Drogon v1.9.13"),
    ("oatpp", "Oat++", "C++", "1.3.1", "Oat++ 1.3.1"),
    ("pistache", "Pistache", "C++", "v0.4.26", "Pistache v0.4.26"),
    ("boost-url", "Boost.URL", "C++", "1.92.0", "boost-1.92.0"),
    ("r3", "r3", "C", "2.0 branch, 83d362f", "set(RB_R3_COMMIT 83d362f"),
    ("uwebsockets", "uWebSockets", "C++", "v20.80.0", "uWebSockets v20.80.0"),
    ("glaze", "glaze", "C++", "v9.0.0", "glaze v9.0.0"),
    ("cpp-httplib", "cpp-httplib", "C++", "v0.58.0", "cpp-httplib v0.58.0"),
    ("matchit", "matchit", "Rust", "0.9.2", 'name = "matchit"\nversion = "0.9.2"'),
    ("actix-router", "actix-router", "Rust", "0.5.4", 'name = "actix-router"\nversion = "0.5.4"'),
    ("path-tree", "path-tree", "Rust", "0.8.3", 'name = "path-tree"\nversion = "0.8.3"'),
    ("httprouter", "httprouter", "Go", "v1.3.0", "github.com/julienschmidt/httprouter v1.3.0"),
    ("gin", "gin", "Go", "v1.12.0", "github.com/gin-gonic/gin v1.12.0"),
    ("nethttp", "net/http", "Go", "1.27.1", 'RB_NETHTTP_GO "go1.27.1'),
    ("chi", "chi", "Go", "v5.3.2", "github.com/go-chi/chi/v5 v5.3.2"),
]
OTHER_VERSIONS = [("VerPcre", "10.49", "pcre2-10.49"), ("VerNanobench", "v4.6.0", "nanobench v4.6.0"),
                  ("VerSmallvec", "1.16.2", 'name = "smallvec"\nversion = "1.16.2"')]
# axum's release and the matchit it pins (design/round2/competitor-survey.md, read again at
# axum-v0.8.9/axum/Cargo.toml; refs.bib, axum2026axum).
AXUM = {"VerAxum": "0.8.9", "VerAxumMatchit": "0.8.4"}
# The runs were built at commits of this repository's earlier, archived history, which the public
# history does not contain. PROVENANCE.md shows that the first-party files the measured builds
# compiled are byte-identical at the root commit of the public history. The paper names the public
# commit beside the measured one. A measured commit not listed here stops the script.
PUBLIC_COMMIT = {
    "90beca488d68d29bf98aa16bce415c3b02892785": "f626955ebd94398a1376af4d48d61ee7a9ca9f6c",  # rbench
    "4cc42bf11ace589f29de6194142c1d8cb7dfd062": "f626955ebd94398a1376af4d48d61ee7a9ca9f6c",  # the server
}

PROBE_CASES = ["static-then-param", "param-then-static", "pchar", "raw-bytes", "catch-all", "empty-segment",
               "trailing-slash", "method"]


def word(arm: str) -> str:
    """A macro-name word for an arm: letters only."""
    special = {"r3": "RThree", "regexmatcher-v2": "VTwo", "regexmatcher-v1": "VOne", "nethttp": "NetHttp",
               "uwebsockets": "UWebSockets", "cpp-httplib": "CppHttplib", "boost-url": "BoostUrl", "oatpp": "Oatpp"}
    if arm in special:
        return special[arm]
    return "".join(p.capitalize() for p in re.split(r"[^A-Za-z]+", arm) if p)


def arm_tt(arm: str) -> str:
    return tt(arm)


def shape_cell(shape: str, m: int) -> str:
    """The shape column of a table: the name on the first size of a shape only."""
    return f"\\shape{{{shape}}}" if m == SIZES[0] else ""


def yes(b: bool) -> str:
    return "yes" if b else "no"


def sig(x: float, digits: int = 3) -> str:
    """Three significant figures, grouped."""
    if x == 0:
        return "0"
    places = digits - 1 - math.floor(math.log10(abs(x)))
    return fixed(round(x, places), max(0, places))


def math_sci(x: float) -> str:
    return f"${scientific(x)}$"


def fl(v: str) -> float:
    return float(v)


def truth(v: str) -> bool:
    return str(v) == "True"


def check(cond: bool, what: str) -> None:
    if not cond:
        raise SystemExit(f"paper_macros: a fact the paper states is false: {what}")


# ------------------------------------------------------------------------------ Sections

def versions(mc: Macros) -> None:
    sources = "\n".join((PAPER / p).read_text(encoding="utf-8").replace("\r\n", "\n") for p in
                        ("bench/cmake/pins.cmake", "bench/arms/rust/Cargo.lock", "bench/arms/go/go.mod"))
    for key, _name, _lang, shown, must in COMPETITORS:
        check(must in sources, f"version of {key} ({must}) in the pins")
        mc.add("Ver" + word(key), shown)
    for name, shown, must in OTHER_VERSIONS:
        check(must in sources, f"{name} ({must}) in the pins")
        mc.add(name, shown)
    for name, v in AXUM.items():
        mc.add(name, v, "competitor-survey.md, axum-v0.8.9/axum/Cargo.toml")


def public_commit(measured: str) -> str:
    """The public-history commit with the same compiled files as the measured commit."""
    if measured not in PUBLIC_COMMIT:
        raise SystemExit(f"paper_macros: code commit {measured} is not in PUBLIC_COMMIT (see PROVENANCE.md)")
    return PUBLIC_COMMIT[measured]


def provenance(mc: Macros, s: dict, run: Path) -> None:
    prov = s["provenance"]
    mc.add("PreSpecCommit", tt(prov["repo_head"][:7]), "the commit that froze hypotheses-round2.md")
    mc.add("RegexMatcherCommitFull", prov["regexmatcher_commit"])
    mc.add("RbenchCommitFull", prov["code_commit"])
    mc.add("RbenchPublicCommitFull", public_commit(prov["code_commit"]),
           "the root of the published history, the same compiled files (PROVENANCE.md)")
    pins = (PAPER / "bench/cmake/pins.cmake").read_text(encoding="utf-8")
    v1 = re.search(r"set\(RB_REGEXMATCHER_COMMIT_V1 ([0-9a-f]+)\)", pins).group(1)
    mc.add("RegexMatcherVOneCommit", tt(v1[:8]))
    mc.add("RegexMatcherVOneCommitFull", v1)
    server = json.loads((RECORDS / "mserver-4cc42bf11-L-asan.json").read_text(encoding="utf-8"))
    mc.add("ServerCommit", tt(server["commit"][:9]))
    mc.add("ServerPublicCommit", tt(public_commit(server["commit"])[:9]),
           "the root of the published history, the same compiled files (PROVENANCE.md)")
    tool = dict(l.split(": ", 1) for l in (run / "toolchain.txt").read_text(encoding="utf-8").splitlines()
                if ": " in l)
    clang = re.search(r"clang version (\S+)", tool["cxx"]).group(1)
    check(f"Clang {clang}" == prov["compiler"], "the compiler of the run")
    mc.add("ClangVersion", clang)
    mc.add("RustcVersion", re.search(r"rustc (\S+)", tool["rustc"]).group(1))
    mc.add("GoVersion", re.search(r"go(\d+\.\d+\.\d+)", tool["go"]).group(1))
    msvc = [json.loads(l) for l in (EVIDENCE / "2026-10-01-W-ct-msvc/tables.jsonl").read_text(encoding="utf-8")
            .splitlines() if l.startswith("{")]
    names = {r["compiler"] for r in msvc}
    check(len(names) == 1, "one MSVC version")
    mc.add("MsvcVersion", re.search(r"MSVC (\d+\.\d+\.\d+)", names.pop()).group(1))
    pin = json.loads((EVIDENCE / "2026-10-01-L-publication-main-grid/pin.json").read_text(encoding="utf-8"))
    mc.add("KernelVersion", pin["kernel"].split("-")[0])
    mc.add("MeanMhz", count(pin["mean_mhz"]), "pin.json")
    mc.add("HostLCpu", re.sub(r" with .*", "", s["env"]["cpu_model"]))
    isa = (EVIDENCE / "2026-10-01-L-publication-main-grid/rb_isa.h").read_text(encoding="utf-8")
    mc.add("TargetCpu", re.search(r'RB_ISA_TARGET_CPU "(\w+)"', isa).group(1))
    mc.add("GoAmdLevel", re.search(r'RB_ISA_GOAMD64 "(\w+)"', isa).group(1))
    cpu = s["env"]["cpu"]
    m = re.match(r"(\d+) \(thread siblings: (\d+)-(\d+)\)", cpu)
    mc.add("TimedCpu", m.group(1))
    mc.add("TimedCpuSibling", m.group(3) if m.group(2) == m.group(1) else m.group(2))
    mc.add("ProcessBudgetSeconds", count(int(s["env"]["cell_timeout_s"])))


def design(mc: Macros, s: dict, run: Path) -> None:
    env = s["env"]
    sizes = [int(x) for x in env["sizes"].split()]
    check(sizes == SIZES, "the sizes")
    for m in sizes:
        mc.add("Size" + SIZE_WORD[m], count(m))
    pairs = [p.split(":") for p in env["pairs (table_seed:ring_seed)"].split()]
    mc.add("TableSeedFirst", pairs[0][0])
    mc.add("TableSeedLast", pairs[-1][0])
    mc.add("RingSeedFirst", pairs[0][1])
    mc.add("RingSeedLast", pairs[-1][1])
    mc.add("HSixTableSeed", pairs[0][0], "H6 serves the first pair")
    mc.add("HSixRingSeed", pairs[0][1])
    scope = dict(x.split(":", 1) for x in env["scope"].split())
    m_max, reps = {v.split(":")[0] for v in scope.values()}, {v.split(":")[1] for v in scope.values()}
    check(len(m_max) == 1 and len(reps) == 1, "one scope for the slow reference arms")
    mc.add("RefMaxSize", count(int(m_max.pop())))
    mc.add("RefReps", reps.pop())
    mc.add("Margin", ratio(s["h1"]["margin"]).rstrip("0"), "section 6, H1 and H7")
    mc.add("MarginPct", fixed(100 * (s["h1"]["margin"] - 1), 0))
    mc.add("HOneCapTwo", fixed(s["h1"]["cap"], 2), "H1's cap on the upper bound")
    for k, (v, note) in FROZEN.items():
        mc.add(k, v, note)
    for k, v in H6_FROZEN.items():
        mc.add(k, v, "hypotheses-round2.md, H6")
    for k, v in V2_LIMITS.items():
        mc.add("VTwo" + k, v, "RegexMatcher d1d73e9, route/config.hpp and route/table.hpp")
    first = json.loads((run / "cells.jsonl").open(encoding="utf-8").readline())
    mc.add("RingSize", count(first["ring_size"]))
    n = s["reps"]
    cells = s["h1"]["cells"]
    alpha = 0.025
    mc.add("HolmFirst", math_sci(alpha / cells), "alpha over the family's 35 cells")
    mc.add("SignMinP", math_sci(2.0 ** -n), "2^-R")
    mc.add("BootMinP", math_sci(1 / (2 * s["resamples"])), "the clipped share, 1/(2B)")
    mc.add("SignOneAbove", math_sci(sum(math.comb(n, k) for k in range(n - 1, n + 1)) / 2 ** n))
    need = next(x for x in range(n + 1) if sum(math.comb(n, k) for k in range(x, n + 1)) / 2 ** n <= alpha)
    mc.add("HSevenSignNeed", str(need), "fewest of 16 pairs below 1.02 for the exact sign test at 0.025")
    mc.add("HSixSignMinP", math_sci(2.0 ** -int(H6_FROZEN["HSixMinPairs"])), "2^-6")


def run_counts(mc: Macros, results: Path, run: Path) -> None:
    rows = read_csv(results / "all_arms.csv")
    statuses = Counter()
    for r in rows:
        for part in r["statuses"].split(", "):
            k, _, v = part.rpartition(" ")
            statuses[k] += int(v)
    mc.add("RunProcesses", count(sum(int(r["processes"]) for r in rows)))
    mc.add("RunOk", count(statuses["ok"]))
    mc.add("RunRefused", count(statuses["refused"]))
    mc.add("RunDeclared", count(statuses["disagrees"]))
    check(set(statuses) == {"ok", "refused", "disagrees"}, "every process ok, refused or declared")
    arms = {r["arm"] for r in rows}
    mc.add("RunArms", count(len(arms)))
    first = [json.loads(l) for l in (run / "verified.jsonl").read_text(encoding="utf-8").splitlines() if l]
    repeat = [json.loads(l) for l in (run / "verified-repeat.jsonl").read_text(encoding="utf-8").splitlines() if l]
    killed = sum("exit -9" in str(r.get("check", {}).get("reason", "")) for r in first)
    mc.add("VerifyCut", count(len(first)))
    mc.add("VerifyKilled", count(killed))
    check(len(repeat) == len(first) and all(r["agrees_all"] and r["digests_match"] for r in repeat),
          "every repeated check agreed")
    mc.add("VerifyRepeatAgreed", count(sum(r["agrees_all"] for r in repeat)))
    cut_arms = Counter(r["arm"] for r in first)
    mc.add("VerifyCutActix", count(cut_arms["actix-router"]))
    check(not any(r["check"].get("reason", "").startswith("wrong") for r in first), "no wrong answer in the first check")


def h1(mc: Macros, s: dict, results: Path) -> None:
    rows = read_csv(results / "h1.csv")
    check(all(not truth(r["cut_v2"]) and not truth(r["cut_fastest"]) for r in rows), "no H1 cell was cut")
    check(max(abs(fl(r["a"])) for r in rows if r["a"]) < 1e-9, "the BCa acceleration is zero")
    check(all("exceeds budget" not in r["absent"] for r in rows), "no competitor over the budget")
    sup = [r for r in rows if truth(r["superior"])]
    mc.add("HOneSupRatioMin", ratio(min(fl(r["ratio"]) for r in sup)))
    mc.add("HOneSupRatioMax", ratio(max(fl(r["ratio"]) for r in sup)))
    mc.add("HOneNotSuperior", count(len(rows) - len(sup)))
    mc.add("HOneMaxAccel", math_sci(max(abs(fl(r["a"])) for r in rows if r["a"] and fl(r["a"]) != 0)),
           "the largest |a| of the jackknife")
    fastest = Counter(r["fastest"] for r in rows)
    for arm in ("gin", "matchit", "uwebsockets", "glaze"):
        mc.add(f"HOneFastest{word(arm)}Cells", count(fastest[arm]))
    check(sum(fastest[a] for a in ("gin", "matchit", "uwebsockets", "glaze")) == len(rows), "four fastest arms")
    for r in rows:
        m = int(r["m"])
        w = cell_word(r["shape"], m)
        p_ni = max(fl(r["p_boot_holm"]), fl(r["p_sign_holm"]))
        p_sup = max(fl(r["p_boot_sup_holm"]), fl(r["p_sign_sup_holm"]))
        mc.add(f"HOneVtwoNs{w}", nanoseconds(fl(r["v2_ns"])))
        mc.add(f"HOneFastestNs{w}", nanoseconds(fl(r["fastest_ns"])))
        mc.add(f"HOneSignXSup{w}", count(int(r["sign_x_sup"])))
        mc.add(f"HOneSuperior{w}", yes(truth(r["superior"])))
        mc.add(f"HOneCompetitors{w}", count(len(r["competitors"].split())))
        mc.add(f"HOneRow{w}", " & ".join([
            shape_cell(r["shape"], m), count(m), arm_tt(r["fastest"]), count(len(r["competitors"].split())),
            nanoseconds(fl(r["v2_ns"])), nanoseconds(fl(r["fastest_ns"])), ratio(fl(r["ratio"])),
            f"[{ratio(fl(r['ci_low']))}, {ratio(fl(r['ci_high']))}]", count(int(r["sign_x"])), math_sci(p_ni),
            yes(truth(r["passes"])), math_sci(p_sup), yes(truth(r["superior"]))]))
    # mixed-disjoint at m = 10 before the repeated check (the frozen analysis of the run as it
    # stood, lab evidence 2026-10-01-L-publication-main-grid/analysis-asis).
    asis = json.loads((EVIDENCE / "2026-10-01-L-publication-main-grid/analysis-asis/summary.json")
                      .read_text(encoding="utf-8"))
    mc.add("HOneAsIsPassed", count(asis["h1"]["passed"]))
    mc.add("HOneAsIsTested", count(asis["h1"]["tested"]))
    mc.add("HOneAsIsUntested", count(asis["h1"]["cells"] - asis["h1"]["tested"]))
    before = next(c for c in asis["h1_cells"] if c["shape"] == "mixed-disjoint" and c["m"] == 10)
    after = next(c for c in s["h1_cells"] if c["shape"] == "mixed-disjoint" and c["m"] == 10)
    check(before["p_sign"] == after["p_sign"], "the raw sign-test p of mixed-disjoint m = 10 is unchanged")
    mc.add("HOnePSignHolmBeforeMixedDisjointTen", math_sci(before["p_sign_holm"]))
    mc.add("HOnePBootRawBeforeMixedDisjointTen", math_sci(before["p_boot"]))
    mc.add("HOnePBootHolmBeforeMixedDisjointTen", math_sci(before["p_boot_holm"]))
    for name, cells in (("Before", asis["h1_cells"]), ("After", s["h1_cells"])):
        ps = sorted((c["p_sign"] if c["status"] == "tested" else 1.0, i) for i, c in enumerate(cells))
        idx = next(i for i, c in enumerate(cells) if c["shape"] == "mixed-disjoint" and c["m"] == 10)
        rank = next(k for k, (_, i) in enumerate(ps, 1) if i == idx)
        mc.add(f"HOneHolmMultiplier{name}MixedDisjointTen", count(len(cells) - rank + 1),
               "Holm's multiplier of the cell's sign-test p, by its rank")


def h2(mc: Macros, s: dict, results: Path) -> None:
    rows = read_csv(results / "h2.csv")
    cut = sorted({a for r in rows for a in r["cut_competitors"].split() if a})
    mc.add("HTwoCutArms", ", ".join(tt(a) for a in cut[:-1]) + " and " + tt(cut[-1]))
    for r in rows:
        m = int(r["m"])
        w = cell_word(r["shape"], m)
        bm_uncut = fl(r["median_competitor_branch_misses_uncut"])
        bm = fl(r["median_competitor_branch_misses"])
        mc.add(f"HTwoVtwoNet{w}", instructions(fl(r["v2_instructions_net"])))
        mc.add(f"HTwoFastestNet{w}", instructions(fl(r["fastest_instructions_net"])))
        mc.add(f"HTwoRow{w}", " & ".join([
            shape_cell(r["shape"], m), count(m), arm_tt(r["fastest"]),
            instructions(fl(r["v2_instructions_net"])), instructions(fl(r["fastest_instructions_net"])),
            instructions(fl(r["v2_instructions_raw"])), instructions(fl(r["fastest_instructions_raw"])),
            per_lookup(fl(r["v2_branch_misses"])), per_lookup(bm),
            per_lookup(bm_uncut) if r["cut_competitors"] else "", yes(truth(r["holds"]))]))
        if not truth(r["holds"]):
            for k, kw in (("l1d", "LOneD"), ("l2", "LTwo"), ("dtlb", "Dtlb")):
                places = 4 if k == "l2" else 2
                mc.add(f"HTwoVtwo{kw}{w}", fixed(fl(r[f"v2_{k}_misses"]), places))
                mc.add(f"HTwoFastest{kw}{w}", fixed(fl(r[f"fastest_{k}_misses"]), places))
            mc.add(f"HTwoVtwoBm{w}", per_lookup(fl(r["v2_branch_misses"])))
            mc.add(f"HTwoMedianBm{w}", per_lookup(bm))


def h3(mc: Macros, s: dict) -> None:
    arms = s["h3"]["arms"]
    mc.add("HThreeCtProcesses", count(arms["regexmatcher-v2-ct"]["processes"]))
    mc.add("HThreeAblationProcesses", count(arms["regexmatcher-v2-r1"]["processes"]))


def h4(mc: Macros, s: dict, results: Path) -> None:
    rows = read_csv(results / "h4.csv")
    lost = [r for r in rows if not truth(r["holds"])]
    check(all(not truth(r["build_holds"]) and truth(r["heap_holds"]) for r in lost), "H4 lost on build time only")
    worst = max(lost, key=lambda r: fl(r["build_s"]) / fl(r["median_competitor_build_s"]))
    best = min(lost, key=lambda r: fl(r["build_s"]) / fl(r["median_competitor_build_s"]))
    mc.add("HFourLostRatioMin", multiple(fl(best["build_s"]) / fl(best["median_competitor_build_s"])))
    mc.add("HFourLostRatioMax", multiple(fl(worst["build_s"]) / fl(worst["median_competitor_build_s"])))
    big = [r for r in rows if int(r["m"]) == SIZES[-1]]
    mc.add("HFourBuildMaxMs", sig(1e3 * max(fl(r["build_s"]) for r in big)), "v2's slowest build at m = 100,000")
    heap = [fl(r["table_bytes"]) / fl(r["smallest_competitor_bytes"]) for r in rows]
    mc.add("HFourHeapRatioMax", multiple(max(heap)))
    mc.add("HFourHeapRatioMin", multiple(min(heap)))
    for r in rows:
        m = int(r["m"])
        w = cell_word(r["shape"], m)
        mc.add(f"HFourRow{w}", " & ".join([
            shape_cell(r["shape"], m), count(m), sig(1e6 * fl(r["build_s"])),
            sig(1e6 * fl(r["median_competitor_build_s"])), count(int(fl(r["table_bytes"]))),
            count(int(fl(r["smallest_competitor_bytes"]))), arm_tt(r["smallest_competitor"]),
            yes(truth(r["build_holds"])), yes(truth(r["heap_holds"])), yes(truth(r["holds"]))]))


def h5(mc: Macros, s: dict, results: Path) -> None:
    for san in ("asan", "tsan", "msan"):
        rec = json.loads((RECORDS / f"regexmatcher-d1d73e99b-L-{san}.json").read_text(encoding="utf-8"))
        check(rec["green"] and rec["tests_failed"] == 0 and rec["sanitizer_reports"] == 0, f"RegexMatcher {san}")
        if san == "asan":
            mc.add("HFiveATests", count(rec["tests_total"]))
            mc.add("HFiveAFailed", count(rec["tests_failed"]))
        srv = json.loads((RECORDS / f"mserver-4cc42bf11-L-{san}.json").read_text(encoding="utf-8"))
        check(srv["green"] and srv["ctest_exit"] == 0 and srv["sanitizer_reports"] == 0, f"server {san}")
    rows = read_csv(results / "h5b.csv")
    by = {}
    for r in rows:
        by.setdefault(r["arm"], {})[r["case"]] = (int(r["passed"]), int(r["failed"]))
    order = ["regexmatcher-v2", "regexmatcher-v1"] + sorted(a for a in by if not a.startswith("regexmatcher")
                                                              and a not in ("radix", "hash", "std-regex"))
    for arm in order:
        cases = by[arm]
        cells = []
        for c in PROBE_CASES:
            p, f = cases.get(c, (0, 0))
            cells.append("$\\circ$" if p + f == 0 else ("$\\checkmark$" if f == 0 else "$\\times$"))
        mc.add(f"ProbeRow{word(arm)}", " & ".join([arm_tt(arm)] + cells))
    check(all(f == 0 for p, f in by["regexmatcher-v2"].values()), "v2 passes every probe")
    mc.add("ProbeArms", " ".join(f"\\ProbeRow{word(a)}\\\\" for a in order))


def h6(mc: Macros, s: dict, results: Path, run: Path) -> None:
    rows = read_csv(results / "h6.csv")
    check(all(not r["left_out"] for r in rows), "no H6 window invalid")
    windows = sum(int(r["pairs"]) * 6 for r in rows)
    mc.add("HSixWindows", count(windows), "pairs times six windows (two per arm)")
    mc.add("HSixVtwoRpsMin", count(round(min(fl(r["v2_rps"]) for r in rows))))
    mc.add("HSixVtwoRpsMax", count(round(max(fl(r["v2_rps"]) for r in rows))))
    mc.add("HSixNullUsMin", multiple(min(fl(r["null_us_per_request"]) for r in rows)))
    mc.add("HSixNullUsMax", multiple(max(fl(r["null_us_per_request"]) for r in rows)))
    mc.add("HSixPredMin", ratio(min(fl(r["measured_over_predicted"]) for r in rows)))
    mc.add("HSixPredMax", ratio(max(fl(r["measured_over_predicted"]) for r in rows)))
    small = [r for r in rows if r["cell"].endswith("-10")]
    mc.add("HSixLowMinTen", ratio(min(fl(r["ratio_ci_low"]) for r in small)))
    mc.add("HSixLowMaxTen", ratio(max(fl(r["ratio_ci_low"]) for r in small)))
    mc.add("HSixCarryLowMin", ratio(min(fl(r["carry_ci_low"]) for r in rows)))
    mc.add("HSixCarryLowMax", ratio(max(fl(r["carry_ci_low"]) for r in rows)))
    check(all(int(r["sign_a_x"]) == int(r["pairs"]) and int(r["sign_b_x"]) == int(r["pairs"]) for r in rows),
          "every H6 pair above 1 and every carry-over at least 0.5")
    # The prefix of the ring that v1's T0 time rests on, at pair (111, 211) (section 6, H6(b)).
    want = {("rest", 10000), ("param-last", 10000)}
    prefix = {}
    with (run / "cells.jsonl").open(encoding="utf-8") as f:
        for line in f:
            if '"regexmatcher-v1"' not in line:
                continue
            d = json.loads(line)
            if d["arm"] == "regexmatcher-v1" and (d["shape"], d["m"]) in want and d["table_seed"] == 111:
                prefix[(d["shape"], d["m"])] = d["lookups_per_pass"]
    for (shape, m), n in prefix.items():
        mc.add(f"HSixVOnePrefix{cell_word(shape, m)}", count(n), "lookups_per_pass of v1 at pair (111, 211)")
    for r in rows:
        shape, _, m = r["cell"].rpartition("-")
        m = int(m)
        w = cell_word(shape, m)
        mc.add(f"HSixRow{w}", " & ".join([
            f"\\shape{{{shape}}}", count(m), count(int(r["pairs"])), count(round(fl(r["v1_rps"]))),
            count(round(fl(r["v2_rps"]))), ratio(fl(r["ratio"])), ratio(fl(r["ratio_ci_low"])),
            nanoseconds(fl(r["d_t0_ns"])), nanoseconds(fl(r["d_meas_ns"])), ratio(fl(r["carry"])),
            ratio(fl(r["carry_ci_low"])), ratio(fl(r["measured_over_predicted"]))]))


def h7(mc: Macros, s: dict, results: Path) -> None:
    rows = read_csv(results / "h7.csv")
    lost = [r for r in rows if not truth(r["holds"])]
    check(len(lost) == 1 and truth(lost[0]["boot_holds"]) and not truth(lost[0]["sign_holds"]),
          "H7 lost one cell, on the sign test only")
    r = lost[0]
    mc.add("HSevenLostCell", f"\\shape{{{r['shape']}}} at $m={count(int(r['m']))}$")
    mc.add("HSevenLostSignX", count(int(r["sign_x"])))
    mc.add("HSevenLostPSign", math_sci(fl(r["p_sign"])))
    mc.add("HSevenLostMaxPair", ratio(fl(r["max_pair_ratio"])))
    mc.add("HSevenLostRatio", ratio(fl(r["ratio"])))
    mc.add("HSevenLostHigh", ratio(fl(r["ci_high"])))
    mc.add("HSevenLostLow", ratio(fl(r["ci_low"])), "the lower bound of the lost cell's 95% BCa interval")
    check(fl(r["ci_low"]) > 1.0, "the lost H7 cell's interval lies wholly above one")
    n = s["reps"]
    need = next(x for x in range(n + 1) if sum(math.comb(n, k) for k in range(x, n + 1)) / 2 ** n <= 0.025)
    mc.add("HSevenAllowedAbove", count(n - need), "pairs at or above the margin that the sign test allows")
    for r in rows:
        m = int(r["m"])
        w = cell_word(r["shape"], m)
        mc.add(f"HSevenRow{w}", " & ".join([
            shape_cell(r["shape"], m) if m == 10 else "", count(m), nanoseconds(fl(r["ct_ns"])),
            nanoseconds(fl(r["rt_ns"])), ratio(fl(r["ratio"])), ratio(fl(r["ci_high"])), count(int(r["sign_x"])),
            math_sci(fl(r["p_sign"])), yes(truth(r["boot_holds"])), yes(truth(r["sign_holds"])),
            yes(truth(r["holds"]))]))


def h7_costs(mc: Macros, results: Path) -> None:
    rows = read_csv(results / "h7_costs.csv")
    msvc = [json.loads(l) for l in (EVIDENCE / "2026-10-01-W-ct-msvc/tables.jsonl").read_text(encoding="utf-8")
            .splitlines() if l.startswith("{")]
    mc.add("CostTables", count(len(rows)))
    mc.add("CostTablesPerSize", count(sum(1 for r in rows if r["m"] == "10")))
    mc.add("MsvcTables", count(len(msvc)))
    over = [int(r["object_not_loadable_bytes"]) for r in rows]
    mc.add("CostPadMin", count(min(over)))
    mc.add("CostPadMax", count(max(over)))
    needs = [int(r["steps_min_passed"]) for r in rows if r["steps_min_passed"]]
    mc.add("ClangNeedMax", count(max(needs)))
    check(int(FROZEN["ConstexprSteps"][0].replace("{,}", "")) == 2 * max(needs), "the budget is twice the largest need")

    def rng(vals: list, fmt) -> str:
        lo, hi = min(vals), max(vals)
        return fmt(lo) if fmt(lo) == fmt(hi) else f"{fmt(lo)} to {fmt(hi)}"

    groups = [("Ten", lambda r: r["m"] == "10"), ("Hundred", lambda r: r["m"] == "100"),
              ("Thousand", lambda r: r["m"] == "1000"), ("Github", lambda r: r["shape"] == "github")]
    for name, sel in groups:
        g = [r for r in rows if sel(r)]
        st = [int(r["steps_min_passed"]) for r in g if r["steps_min_passed"]]
        mw = [r for r in msvc if (r["shape"] == "github" if name == "Github" else
                                 r["m"] == {"Ten": 10, "Hundred": 100, "Thousand": 1000}[name] and r["shape"] != "github")]
        label = f"GitHub, {count(int(g[0]['m']))}" if name == "Github" else count(int(g[0]["m"]))
        mc.add(f"CostRow{name}", " & ".join([
            label, count(len(g)), rng([fl(r["compile_s"]) for r in g], lambda v: fixed(v, 2)),
            rng([int(r["loadable_bytes"]) for r in g], count), rng(st, count),
            rng([r["steps_min_passed"] for r in mw], count),
            rng([r["peak_memory_bytes"] / 2 ** 20 for r in mw], lambda v: count(round(v))),
            rng([r["object_bytes"] for r in mw], count)]))
        if name == "Thousand":
            kinds = {(f["steps"], f["kind"]) for r in mw for f in r.get("failures", [])}
            crash = {st_ for st_, k in kinds if k == "crash"}
            budget = {st_ for st_, k in kinds if k == "budget"}
            check(len(crash) == 1 and len(budget) == 1 and len(kinds) == 2 * len(mw) // len(mw),
                  "every MSVC table of m = 1,000 crashed at one budget and failed at one")
            check(all(len(r["failures"]) == 2 for r in mw), "two failures per MSVC table of m = 1,000")
            mc.add("MsvcCrashSteps", count(crash.pop()))
            mc.add("MsvcBudgetFailSteps", count(budget.pop()))
            mc.add("MsvcPeakMaxGB", fixed(max(r["peak_memory_bytes"] for r in mw) / 1e9, 1))
            mc.add("MsvcPeakMinGB", fixed(min(r["peak_memory_bytes"] for r in mw) / 1e9, 1))
            mc.add("MsvcPeakMinMiB", count(round(min(r["peak_memory_bytes"] for r in mw) / 2 ** 20)))
            mc.add("MsvcPeakMaxMiB", count(round(max(r["peak_memory_bytes"] for r in mw) / 2 ** 20)))
            mc.add("ClangThousandCompileMin", fixed(min(fl(r["compile_s"]) for r in g), 2))
            mc.add("ClangThousandCompileMax", fixed(max(fl(r["compile_s"]) for r in g), 2))
            mc.add("ClangThousandFailSteps", count(max(int(r["steps_max_failed"]) for r in g if r["steps_max_failed"])))


def explore(mc: Macros, results: Path) -> None:
    gh = read_csv(results / "explore_github.csv")[0]
    mc.add("ExGithubRatio", ratio(fl(gh["ratio"])))
    mc.add("ExGithubFastest", arm_tt(gh["fastest"]))
    mc.add("ExGithubVtwoNet", instructions(fl(gh["v2_net"])))
    mc.add("ExGithubFastestNet", instructions(fl(gh["fastest_net"])))
    mc.add("ExGithubPairs", count(int(gh["pairs"])))
    for run, name in (("miss", "Miss"), ("vocab-long", "Vocab"), ("zipf", "Zipf"), ("no-decoy", "NoDecoy")):
        rows = [r for r in read_csv(results / f"explore_{run}.csv") if r["status"] == "compared"]
        lo = min(rows, key=lambda r: fl(r["ratio"]))
        hi = max(rows, key=lambda r: fl(r["ratio"]))
        above = [r for r in rows if fl(r["v2_net"]) > fl(r["fastest_net"])]
        mc.add(f"Ex{name}Cells", count(len(rows)))
        mc.add(f"Ex{name}Pairs", count(int(rows[0]["pairs"])))
        mc.add(f"Ex{name}RatioMin", ratio(fl(lo["ratio"])))
        mc.add(f"Ex{name}RatioMinCell", f"\\shape{{{lo['shape']}}} at $m={count(int(lo['m']))}$")
        mc.add(f"Ex{name}RatioMax", ratio(fl(hi["ratio"])))
        mc.add(f"Ex{name}RatioMaxCell", f"\\shape{{{hi['shape']}}} at $m={count(int(hi['m']))}$")
        mc.add(f"Ex{name}NetAbove", count(len(above)))
        mc.add(f"Ex{name}Row", " & ".join([
            {"miss": "miss-heavy ring", "vocab-long": "long literals", "zipf": "Zipf ring",
             "no-decoy": "\\shape{mixed-overlap}, no decoys"}[run], count(len(rows)), count(int(rows[0]["pairs"])),
            f"{ratio(fl(lo['ratio']))} to {ratio(fl(hi['ratio']))}", count(len(above))]))
        if run == "miss":
            check(all(int(r["m"]) == 10 for r in above), "the miss-heavy cells with more net instructions are at m = 10")
            check(max(fl(r["ratio"]) for r in rows) < 1, "no miss-heavy cell above 1")
        if run == "no-decoy":
            failed = [r for r in read_csv(results / f"explore_{run}.csv") if r["status"] != "compared"]
            check(len(failed) == 1, "one no-decoy cell fails")
            mc.add("ExNoDecoyFailedSize", count(int(failed[0]["m"])))
            mc.add("ExNoDecoyFailOk", re.search(r"ok in (\d+) of", failed[0]["failures"]).group(1))
            for r in rows:
                mc.add(f"ExNoDecoyRatio{SIZE_WORD[int(r['m'])]}", ratio(fl(r["ratio"])))
                mc.add(f"ExNoDecoyFastest{SIZE_WORD[int(r['m'])]}", arm_tt(r["fastest"]))


def ablation(mc: Macros, s: dict, results: Path) -> None:
    a = s["ablation"]
    mc.add("AbCells", count(a["compared"]))
    mc.add("AbTimeMin", ratio(a["time_ratio_min"]))
    mc.add("AbTimeMax", ratio(a["time_ratio_max"]))
    mc.add("AbInsnMin", ratio(a["instructions_net_ratio_min"]))
    mc.add("AbInsnMax", ratio(a["instructions_net_ratio_max"]))
    mc.add("AbBuildMin", ratio(a["build_ratio_min"]))
    mc.add("AbBuildMax", ratio(a["build_ratio_max"]))
    mc.add("AbHeapMin", ratio(a["heap_ratio_min"]))
    mc.add("AbHeapMax", ratio(a["heap_ratio_max"]))
    rows = read_csv(results / "ablation.csv")
    for r in rows:
        m = int(r["m"])
        w = cell_word(r["shape"], m)
        mc.add(f"AbRow{w}", " & ".join([
            shape_cell(r["shape"], m), count(m), ratio(fl(r["time_ratio"])), ratio(fl(r["instructions_net_ratio"])),
            ratio(fl(r["build_ratio"])), ratio(fl(r["heap_ratio"]))]))
        if (r["shape"], m) == ("wild", 10):
            mc.add("AbTimeWildTen", ratio(fl(r["time_ratio"])))
            mc.add("AbInsnWildTen", ratio(fl(r["instructions_net_ratio"])))
    big = [r for r in rows if int(r["m"]) >= 1000]
    mc.add("AbBuildBigMax", ratio(max(fl(r["build_ratio"]) for r in big)))


def pair_details(mc: Macros, run: Path) -> None:
    """Per-pair facts of two cells the paper discusses, from the main grid's cells.jsonl: H7's lost
    cell (the frozen text reports a lost cell with its counters) and H1's wild m = 10 against the
    ablation arm (the cross-round note)."""
    want = {("param-last", 1000): ("regexmatcher-v2", "regexmatcher-v2-ct"),
            ("wild", 10): ("regexmatcher-v2", "regexmatcher-v2-r1")}
    rows: dict = {}
    with (run / "cells.jsonl").open(encoding="utf-8") as f:
        for line in f:
            if '"regexmatcher-v2' not in line:
                continue
            d = json.loads(line)
            key = (d["shape"], d["m"])
            if key in want and d["arm"] in want[key]:
                rows.setdefault(key, {}).setdefault(d["table_seed"], {})[d["arm"]] = d
    for key, (base, other) in want.items():
        per = rows[key]
        check(len(per) == 16 and all(len(v) == 2 for v in per.values()), f"sixteen pairs of {key}")
        ratios = {s: v[other]["ns_median"] / v[base]["ns_median"] for s, v in per.items()}
        if key == ("param-last", 1000):
            seed = max(ratios, key=ratios.get)
            v = per[seed]
            check(abs(v[other]["instructions"] - v[base]["instructions"]) < 0.5, "equal instructions in the slow pair")
            mc.add("HSevenLostSeed", str(seed))
            mc.add("HSevenLostSeedCyclesCt", fixed(v[other]["cycles"], 1))
            mc.add("HSevenLostSeedCyclesRt", fixed(v[base]["cycles"], 1))
            mc.add("HSevenLostSeedInsn", fixed(v[base]["instructions"], 1))
            others = sorted(r for s, r in ratios.items() if s != seed)
            mc.add("HSevenLostOthersMax", ratio(others[-1]))
            mc.add("HSevenLostAboveMargin", count(sum(r >= 1.02 for r in ratios.values())))
            mc.add("HSevenLostAboveOne", count(sum(r > 1.0 for r in ratios.values())))
        else:
            ratios = {s: v[base]["ns_median"] / v[other]["ns_median"] for s, v in per.items()}
            seed = max(ratios, key=ratios.get)
            v = per[seed]
            check(abs(v[other]["instructions"] - v[base]["instructions"]) < 0.5, "equal instructions, wild 10")
            check(all(abs(x[other]["instructions"] - x[base]["instructions"]) < 0.5 for x in per.values()),
                  "v2 and the ablation arm run equal instructions in every pair of wild m = 10")
            mc.add("WildTenSlowSeed", str(seed))
            mc.add("WildTenSlowRatio", ratio(ratios[seed]))
            mc.add("WildTenSlowCyclesVtwo", fixed(v[base]["cycles"], 1))
            mc.add("WildTenSlowCyclesAb", fixed(v[other]["cycles"], 1))
            others = sorted(r for s, r in ratios.items() if s != seed)
            mc.add("WildTenOthersMin", ratio(others[0]))
            mc.add("WildTenOthersMax", ratio(others[-1]))


def ct_heap(mc: Macros, results: Path) -> None:
    """The exploratory follow-up of H7 (section 7, last item): H7's lost cell again, with the
    compile-time table copied into a heap block in the same binary (explore_ct_heap.csv, written by
    analysis/ct_heap_summary.py). Descriptive: the table seed that stood apart in the main grid,
    its ratios in the follow-up's binary, the other seeds' range and median, and its counters."""
    rows = read_csv(results / "explore_ct_heap.csv")
    check(len(rows) == 16, "the follow-up ran sixteen pairs")
    frozen = {int(r["table_seed"]): fl(r["frozen_ct_rt"]) for r in rows}
    seed = max(frozen, key=frozen.get)
    check(sorted(frozen.values())[-1] > sorted(frozen.values())[-2], "one table seed stood apart in the main grid")
    mc.add("ExCtHeapSeed", str(seed))
    mc.add("ExCtHeapPairs", count(len(rows)))
    apart = next(r for r in rows if int(r["table_seed"]) == seed)
    others = [r for r in rows if int(r["table_seed"]) != seed]
    check(all(max(fl(r[f"{a}_insn"]) for a in ("rt", "ct", "heap")) -
              min(fl(r[f"{a}_insn"]) for a in ("rt", "ct", "heap")) < 0.05 for r in rows),
          "the three arms run equal instructions in every pair of the follow-up")
    for key, name in (("heap_rt", "HeapRt"), ("ct_rt", "CtRt"), ("heap_ct", "HeapCt")):
        lo = min(others, key=lambda r: fl(r[key]))
        hi = max(others, key=lambda r: fl(r[key]))
        mc.add(f"ExCtHeap{name}Seed", ratio(fl(apart[key])))
        mc.add(f"ExCtHeap{name}OthersMin", ratio(fl(lo[key])))
        mc.add(f"ExCtHeap{name}OthersMinSeed", str(int(lo["table_seed"])))
        mc.add(f"ExCtHeap{name}OthersMax", ratio(fl(hi[key])))
        mc.add(f"ExCtHeap{name}OthersMaxSeed", str(int(hi["table_seed"])))
        mc.add(f"ExCtHeap{name}OthersMedian", ratio(statistics.median(fl(r[key]) for r in others)))
        mc.add(f"ExCtHeap{name}Median", ratio(statistics.median(fl(r[key]) for r in rows)))
    for arm, name in (("rt", "Rt"), ("ct", "Ct"), ("heap", "Heap")):
        slow = max(rows, key=lambda r: fl(r[f"{arm}_cycles"]))
        mc.add(f"ExCtHeapCycles{name}Max", fixed(fl(slow[f"{arm}_cycles"]), 1))
        mc.add(f"ExCtHeapCycles{name}MaxSeed", str(int(slow["table_seed"])))
        mc.add(f"ExCtHeapCycles{name}Median", fixed(statistics.median(fl(r[f"{arm}_cycles"]) for r in rows), 1))
        mc.add(f"ExCtHeapNs{name}Seed", nanoseconds(fl(apart[f"{arm}_ns"])))
        mc.add(f"ExCtHeapInsn{name}Seed", instructions(fl(apart[f"{arm}_insn"])))
        mc.add(f"ExCtHeapCycles{name}Seed", fixed(fl(apart[f"{arm}_cycles"]), 1))
        mc.add(f"ExCtHeapLOneD{name}Seed", per_lookup(fl(apart[f"{arm}_l1d"])))
        mc.add(f"ExCtHeapDtlb{name}Seed", sig(fl(apart[f"{arm}_dtlb"])))
        mc.add(f"ExCtHeapLOneD{name}Median", per_lookup(statistics.median(fl(r[f"{arm}_l1d"]) for r in rows)))
        mc.add(f"ExCtHeapDtlb{name}Median", sig(statistics.median(fl(r[f"{arm}_dtlb"]) for r in rows)))
        mc.add(f"ExCtHeapInsn{name}Median", instructions(statistics.median(fl(r[f"{arm}_insn"]) for r in rows)))


def coverage_gap(mc: Macros) -> None:
    """The arms that MemorySanitizer's record leaves out (bench/coverage.json)."""
    cov = json.loads((PAPER / "bench/coverage.json").read_text(encoding="utf-8"))
    gap = [k for k, v in cov.items() if k.startswith("arm_") and "msan" in v.get("not_covered_by", [])]
    mc.add("MsanGapArms", count(len(gap)), "bench/coverage.json")


def explore_archives(mc: Macros) -> None:
    """The five exploratory archives and their sha256 (lab/evidence/2026-10-01-L-exploratory)."""
    names = {"github": "Github", "miss": "Miss", "no-decoy": "NoDecoy", "vocab-long": "Vocab", "zipf": "Zipf"}
    for run, word_ in names.items():
        f = EVIDENCE / f"2026-10-01-L-exploratory/p2-raw-2026-09-30-L-exploratory-{run}.tar.gz.sha256"
        sha, file = f.read_text(encoding="utf-8").split()[:2]
        check(re.fullmatch(r"[0-9a-f]{64}", sha) is not None, f"sha256 of the {run} archive")
        mc.add(f"ArchiveEx{word_}", Path(file.lstrip("*")).name)
        mc.add(f"ArchiveEx{word_}Sha", sha)


def archives(mc: Macros) -> None:
    items = [("Main", "2026-10-01-L-publication-main-grid/p2-raw-2026-09-30-L-publication.tar.gz.sha256"),
             ("Verify", "2026-10-01-L-publication-recheck/p2-raw-2026-09-30-L-publication-verify-repeat.tar.gz.sha256"),
             ("Ct", "2026-10-01-L-publication-ct/p2-raw-2026-09-30-L-publication-ct.tar.gz.sha256"),
             ("HSix", "2026-10-01-L-publication-h6/p2-raw-2026-09-30-L-h6.tar.gz.sha256"),
             ("Msvc", "2026-10-01-W-ct-msvc/p2-raw-2026-10-01-W-ct-msvc.tar.gz.sha256"),
             ("CtHeap", "2026-10-02-L-exploratory-ct-heap/p2-raw-2026-10-02-L-exploratory-ct-heap.tar.gz.sha256")]
    for name, rel in items:
        sha, file = (EVIDENCE / rel).read_text(encoding="utf-8").split()[:2]
        check(re.fullmatch(r"[0-9a-f]{64}", sha) is not None, f"sha256 of {rel}")
        mc.add(f"Archive{name}", Path(file.lstrip("*")).name)
        mc.add(f"Archive{name}Sha", sha)


def render(results: Path, run: Path) -> str:
    s = json.loads((results / "summary.json").read_text(encoding="utf-8"))
    mc = Macros()
    versions(mc)
    provenance(mc, s, run)
    design(mc, s, run)
    run_counts(mc, results, run)
    h1(mc, s, results)
    h2(mc, s, results)
    h3(mc, s)
    h4(mc, s, results)
    h5(mc, s, results)
    h6(mc, s, results, run)
    h7(mc, s, results)
    h7_costs(mc, results)
    explore(mc, results)
    ablation(mc, s, results)
    pair_details(mc, run)
    ct_heap(mc, results)
    archives(mc)
    explore_archives(mc)
    coverage_gap(mc)
    return HEAD + mc.text()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--results", type=Path, default=PAPER / "results/round2")
    ap.add_argument("--run", type=Path, default=Path("D:/Archive/p2-raw/runs/2026-09-30-L-publication"),
                    help="the unpacked main grid (toolchain.txt, cells.jsonl, verified*.jsonl)")
    ap.add_argument("--out", type=Path)
    a = ap.parse_args()
    if a.results.resolve() == (PAPER / "results").resolve():
        raise SystemExit("paper_macros: results/ is round 1; give results/round2")
    text = render(a.results, a.run)
    if a.out:
        a.out.write_text(text, encoding="utf-8", newline="\n")
    else:
        print(text, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
