// gen_route_tests: the paper's tables as test data for RegexMatcher v2's compile-time-table tests
// (tests/route/ct_tables/ of RegexMatcher). Per shape at m = 10, 100 and 1,000 and the GitHub
// table, table seed 1 (an engineering seed, never a held-out one): the routes, and 64 queries
// (48 of ring seed 2, 16 misses of ring seed 3) with the route and values each must find, as
// the harness's reference matcher answers them.
//
//     gen_route_tests OUT_DIR
//
// Built from bench/core only (bench/tools/CMakeLists.txt), so it needs no arm and no fetched
// code.
#include <cstdio>
#include <fstream>
#include <string>
#include <utility>
#include <vector>

#include "core/table.hpp"

namespace {

std::string cxx_string(const std::string& s) {
    std::string out = "\"";
    for (const char c : s) {
        if (c == '"' || c == '\\') {
            out += '\\';
        }
        out += c;
    }
    return out + "\"";
}

}  // namespace

int main(int argc, char** argv) {
    if (argc != 2) {
        std::fprintf(stderr, "usage: gen_route_tests OUT_DIR\n");
        return 2;
    }
    const std::string dir = argv[1];
    std::vector<std::pair<rb::Shape, std::uint32_t>> tables;
    for (rb::Shape sh : rb::kShapes) {
        for (std::uint32_t m : {10u, 100u, 1000u}) {
            tables.emplace_back(sh, m);
        }
    }
    tables.emplace_back(rb::Shape::Github, rb::kGithubRoutes);
    for (const auto& [sh, m] : tables) {
        const rb::Table t = rb::generate_table({sh, m, 1, 1});
        const rb::Ring hits = rb::generate_ring(t, {48, 2, 0});
        const rb::Ring misses = rb::generate_ring(t, {16, 3, 1000});
        std::string name(rb::shape_name(sh));
        for (char& c : name) {
            c = c == '-' ? '_' : c;
        }
        name += "_" + std::to_string(t.routes.size());
        const std::string file = dir + "/" + name + ".hpp";
        std::ofstream f(file, std::ios::binary);
        f << "// Generated by gen_route_tests (paper-typed-routing, bench/tools/gen_route_tests.cpp) from the\n"
          << "// paper's table generator: the " << rb::shape_name(sh) << " table of " << t.routes.size()
          << " routes, table seed 1 (digest " << t.digest.substr(0, 16) << "),\n"
          << "// and 64 queries with the route and values each must find. Do not edit.\n"
          << "#pragma once\n\n#include \"ct_table_case.hpp\"\n\nnamespace ct_tables::" << name << "\n{\n"
          << "\tinline constexpr matcher::route::RouteSpec routes[] = {\n";
        for (std::size_t i = 0; i < t.routes.size(); ++i) {
            f << "\t\t{" << static_cast<unsigned>(t.routes[i].method) << "u, " << cxx_string(rb::render(t.routes[i]))
              << ", " << i << "u},\n";
        }
        f << "\t};\n\n\tinline constexpr Probe probes[] = {\n";
        for (const rb::Ring* r : {&hits, &misses}) {
            for (const rb::Query& q : r->queries) {
                f << "\t\t{" << static_cast<unsigned>(q.method) << "u, " << cxx_string(q.path) << ", " << q.expect << "u, {";
                for (std::size_t i = 0; i < q.caps.size(); ++i) {
                    f << (i ? ", " : "") << cxx_string(q.caps[i]);
                }
                f << "}, " << q.caps.size() << "u},\n";
            }
        }
        f << "\t};\n}  // namespace ct_tables::" << name << "\n";
        if (!f) {
            std::fprintf(stderr, "gen_route_tests: cannot write %s\n", file.c_str());
            return 1;
        }
        std::printf("%s %s\n", file.c_str(), t.digest.c_str());
    }
    return 0;
}
